import { Metadata } from "next";
import SidebarNav from "./components/navigations/sidebarnav";

import Navigationbar from "./components/navigations/navigations";

export const metadata: Metadata = {
  title: "Dashboards",
  description: "Generated by create next app",
};

export default function Dashboards({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="bg-slate-300 flex flex-row text-white text-xl">
      <section className="w-[12%] p-4">
        <SidebarNav />
      </section>
      <section className="w-full p-4">
        <Navigationbar />
        {children}
      </section>
    </main>
  );
}
