import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboards",
  description: "Generated by create next app",
};

export default function Dashboards({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="w-full min-h-screen flex lg:flex-row flex-col items-start justify-start">
      <section>Testing Navigations 2</section>
      {children}
    </main>
  );
}
