import { Metadata } from "next";
import "./module.Home.css";
import Navigations from "./components/navigations/navigations";

export const metadata: Metadata = {
  title: "The Hills",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="w-full h-screen">
      <Navigations />
      {children}
    </main>
  );
} 
